// ReactProject/src/components/ParameterTuning.tsx
import { useEffect, useMemo, useState } from 'react';
import '@/assets/css/ParameterTuning.css';
import type { EditableField, ModelVersion } from '@/api/models';
import { useModelStore } from '@/stores/modelStore';

interface Draft {
  key: string;
  section: string;
  target: string;
  field: string;
  label: string;
  unit: string;
  oldValue: string;
  newValue: string;
}
const time = (value: number) => {
  const seconds = Math.max(0, Math.round(value));
  return `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor((seconds % 3600) / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
};
const parseDate = (value: string) =>
  new Date(/[zZ]|[+-]\d\d:\d\d$/.test(value) ? value : `${value}Z`);

export default function ParameterTuning() {
  const store = useModelStore();
  const groups = store.parameterGroups;
  const [groupId, setGroupId] = useState('');
  const [target, setTarget] = useState('');
  const [targets, setTargets] = useState<string[]>([]);
  const [mode, setMode] = useState<'single' | 'batch'>('single');
  const [search, setSearch] = useState('');
  const [drafts, setDrafts] = useState<Record<string, Draft>>({});
  const [summary, setSummary] = useState('');
  const [localError, setLocalError] = useState('');
  const [created, setCreated] = useState<ModelVersion | null>(null);
  const [batchKey, setBatchKey] = useState('');
  const [batchOperation, setBatchOperation] = useState<'set' | 'add' | 'percent'>('set');
  const [batchAmount, setBatchAmount] = useState('');
  const [duration, setDuration] = useState(0);
  const [reportStep, setReportStep] = useState(0);
  const [rainStart, setRainStart] = useState(0);
  const [rainDuration, setRainDuration] = useState(0);
  const [rainfall, setRainfall] = useState(0);
  const group = groups.find((item) => item.id === groupId);
  const objects = group?.objects ?? [];
  const filtered = objects.filter((item) =>
    item.target.toLowerCase().includes(search.toLowerCase()),
  );
  const object = objects.find((item) => item.target === target);
  const selectedObjects = objects.filter((item) => targets.includes(item.target));
  const commonFields =
    selectedObjects[0]?.fields.filter((field) =>
      selectedObjects.every((item) => item.fields.some((candidate) => candidate.key === field.key)),
    ) ?? [];
  const batchField = commonFields.find((field) => field.key === batchKey);
  const draftsList = Object.values(drafts);
  const options = store.simulationOptions;
  const rainOptions = store.rainfallOptions;
  const durationChanged = duration !== options?.duration_seconds;
  const stepChanged = reportStep !== options?.report_step_seconds;
  const rainChanged =
    !!rainOptions &&
    (rainStart !== rainOptions.start_seconds ||
      rainDuration !== rainOptions.duration_seconds ||
      rainfall !== rainOptions.total_rainfall_mm);
  const minStep = Math.max(
    options?.report_step_min_seconds ?? 1,
    Math.ceil(options?.routing_step_seconds ?? 0),
  );
  const outputSteps =
    Number.isInteger(duration) && Number.isInteger(reportStep) && reportStep > 0
      ? Math.floor(duration / reportStep)
      : 0;
  const simulationError = !options
    ? ''
    : !Number.isInteger(duration)
      ? '模拟时长必须是整数秒'
      : duration < options.duration_min_seconds || duration > options.duration_max_seconds
        ? `模拟时长必须在 ${options.duration_min_seconds}～${options.duration_max_seconds} 秒之间`
        : !Number.isInteger(reportStep)
          ? '输出步长必须是整数秒'
          : reportStep < minStep
            ? `输出步长不能小于 ${minStep} 秒`
            : reportStep > duration
              ? '输出步长不能大于模拟时长'
              : options.require_report_step_divisible && duration % reportStep !== 0
                ? '模拟时长必须能被输出步长整除'
                : outputSteps > options.max_output_steps
                  ? `输出时间点不能超过 ${options.max_output_steps} 个`
                  : '';
  const rainError = !rainOptions
    ? ''
    : !Number.isInteger(rainStart) || !Number.isInteger(rainDuration)
      ? '降雨开始时间和时长必须是整数秒'
      : rainStart < 0 || rainDuration <= 0
        ? '降雨开始时间必须不小于 0，降雨时长必须大于 0'
        : rainStart + rainDuration > duration
          ? '降雨结束时间不能超过模拟时长'
          : rainStart % rainOptions.time_step_seconds ||
              rainDuration % rainOptions.time_step_seconds
            ? `降雨开始时间和时长必须是 ${rainOptions.time_step_seconds} 秒的整数倍`
            : !Number.isFinite(rainfall) || rainfall <= 0
              ? '总降雨量必须是大于 0 的有效数值'
              : '';
  const error = localError || simulationError || rainError;
  const nextVersion = Math.max(...store.versions.map((item) => item.version), 0) + 1;
  useEffect(() => {
    setDuration(options?.duration_seconds ?? 0);
    setReportStep(options?.report_step_seconds ?? 0);
  }, [options]);
  useEffect(() => {
    setRainStart(rainOptions?.start_seconds ?? 0);
    setRainDuration(rainOptions?.duration_seconds ?? 0);
    setRainfall(rainOptions?.total_rainfall_mm ?? 0);
  }, [rainOptions]);
  useEffect(() => {
    if (!groups.some((item) => item.id === groupId)) {
      setGroupId(groups[0]?.id ?? '');
      setTarget(groups[0]?.objects[0]?.target ?? '');
    }
  }, [groups, groupId]);
  useEffect(() => {
    if (!objects.some((item) => item.target === target)) setTarget(objects[0]?.target ?? '');
    setTargets([]);
  }, [groupId]);
  useEffect(() => {
    if (!commonFields.some((field) => field.key === batchKey))
      setBatchKey(commonFields[0]?.key ?? '');
  }, [commonFields, batchKey]);
  useEffect(() => {
    setDrafts({});
    setCreated(null);
  }, [store.selectedVersionId]);
  useEffect(() => {
    const handler = (event: Event) => {
      const detail = (event as CustomEvent<{ layerId: string; target: string }>).detail;
      const matched = groups.find(
        (item) =>
          item.map_layer === detail.layerId &&
          item.objects.some((item) => item.target === detail.target),
      );
      if (!matched) return;
      setGroupId(matched.id);
      if (mode === 'batch')
        setTargets((current) =>
          current.includes(detail.target) ? current : [...current, detail.target],
        );
      else setTarget(detail.target);
    };
    window.addEventListener('swmm:map-feature-selected', handler);
    return () => window.removeEventListener('swmm:map-feature-selected', handler);
  }, [groups, mode]);
  const key = (field: EditableField, objectTarget = target) =>
    `${field.section}|${objectTarget}|${field.field}`;
  const value = (field: EditableField) => drafts[key(field)]?.newValue ?? field.value;
  const clear = () => {
    setDrafts({});
    setLocalError('');
    setDuration(options?.duration_seconds ?? 0);
    setReportStep(options?.report_step_seconds ?? 0);
    setRainStart(rainOptions?.start_seconds ?? 0);
    setRainDuration(rainOptions?.duration_seconds ?? 0);
    setRainfall(rainOptions?.total_rainfall_mm ?? 0);
  };
  const stage = (field: EditableField, raw: string) => {
    const numeric = Number(raw);
    if (
      !object ||
      !Number.isFinite(numeric) ||
      numeric < field.minimum ||
      numeric > field.maximum
    ) {
      setLocalError(`${field.label}必须在 ${field.minimum}～${field.maximum} ${field.unit} 之间`);
      return;
    }
    const draftKey = key(field);
    if (numeric === Number(field.value)) {
      setDrafts((current) => {
        const next = { ...current };
        delete next[draftKey];
        return next;
      });
    } else
      setDrafts((current) => ({
        ...current,
        [draftKey]: {
          key: draftKey,
          section: field.section,
          target: object.target,
          field: field.field,
          label: field.label,
          unit: field.unit,
          oldValue: field.value,
          newValue: String(numeric),
        },
      }));
  };
  const applyBatch = () => {
    if (!batchField || !Number.isFinite(Number(batchAmount)))
      return setLocalError('请选择参数并输入有效数值');
    const updates: Record<string, Draft | null> = {};
    for (const item of selectedObjects) {
      const field = item.fields.find((candidate) => candidate.key === batchField.key)!;
      const draftKey = key(field, item.target);
      const current = Number(drafts[draftKey]?.newValue ?? field.value);
      let next = Number(batchAmount);
      if (batchOperation === 'add') next = current + next;
      if (batchOperation === 'percent') next = current * (1 + next / 100);
      next = Number(next.toPrecision(12));
      if (!Number.isFinite(next) || next < field.minimum || next > field.maximum)
        return setLocalError(
          `${item.target} 的${field.label}计算后为 ${next}，超出 ${field.minimum}～${field.maximum} ${field.unit}`,
        );
      updates[draftKey] =
        next === Number(field.value)
          ? null
          : {
              key: draftKey,
              section: field.section,
              target: item.target,
              field: field.field,
              label: field.label,
              unit: field.unit,
              oldValue: field.value,
              newValue: String(next),
            };
    }
    setLocalError('');
    setDrafts((current) => {
      const next = { ...current };
      Object.entries(updates).forEach(([draftKey, draft]) =>
        draft ? (next[draftKey] = draft) : delete next[draftKey],
      );
      return next;
    });
  };
  const save = async () => {
    if (error) return;
    const result = await store.saveAdjustedVersion(
      draftsList.map((draft) => ({
        section: draft.section,
        target: draft.target,
        field: draft.field,
        new_value: draft.newValue,
      })),
      summary || undefined,
      durationChanged || stepChanged
        ? { duration_seconds: duration, report_step_seconds: reportStep }
        : undefined,
      rainChanged
        ? { start_seconds: rainStart, duration_seconds: rainDuration, total_rainfall_mm: rainfall }
        : undefined,
    );
    if (result) {
      setCreated(result.version);
      setSummary('');
      clear();
    }
  };
  const runCreated = async () => {
    const result = await store.runSelectedVersion();
    if (result) window.dispatchEvent(new CustomEvent('swmm:run-completed', { detail: result }));
  };
  const estimate = useMemo(() => {
    if (!options || duration <= 0) return '—';
    const date = new Date(parseDate(options.start_datetime).getTime() + duration * 1000);
    const pad = (part: number) => String(part).padStart(2, '0');
    return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())}:${pad(date.getUTCSeconds())}`;
  }, [duration, options]);
  return (
    <section className="tuning-workspace" aria-label="参数设置">
      <div className="tuning-heading">
        <div>
          <h3>模拟参数设置</h3>
        </div>
        {(durationChanged || stepChanged || rainChanged) && (
          <span>
            {Number(durationChanged) + Number(stepChanged) + Number(rainChanged)} 项待保存
          </span>
        )}
      </div>
      {options && (
        <div className="simulation-settings">
          <div className="simulation-setting-fields">
            <label>
              <span>
                模拟时长 <small>秒</small>
              </span>
              <input
                value={duration}
                type="number"
                min={options.duration_min_seconds}
                max={options.duration_max_seconds}
                step="1"
                onChange={(event) => setDuration(Number(event.target.value))}
              />
              <small>
                {options.duration_min_seconds}～{options.duration_max_seconds} 秒
              </small>
            </label>
            <label>
              <span>
                输出步长 <small>秒</small>
              </span>
              <input
                value={reportStep}
                type="number"
                min={minStep}
                max={duration || undefined}
                step="1"
                onChange={(event) => setReportStep(Number(event.target.value))}
              />
              <small>
                不小于路由步长 {options.routing_step_seconds} 秒
              </small>
            </label>
          </div>
          <div className="simulation-projection">
            <span>预计结束</span>
            <strong>{estimate}</strong>
            <output>{outputSteps} 个输出点</output>
            {options.require_report_step_divisible && <em>时长须能被输出步长整除</em>}
          </div>
        </div>
      )}
      {rainOptions && (
        <div className="rainfall-settings">
          <div className="rainfall-setting-fields">
            <label>
              <span>
                降雨开始 <small>秒</small>
              </span>
              <input
                value={rainStart}
                type="number"
                min="0"
                max={duration}
                step={rainOptions.time_step_seconds}
                onChange={(event) => setRainStart(Number(event.target.value))}
              />
              <small>{time(rainStart)}</small>
            </label>
            <label>
              <span>
                降雨时长 <small>秒</small>
              </span>
              <input
                value={rainDuration}
                type="number"
                min="0"
                max={Math.max(0, duration - rainStart)}
                step={rainOptions.time_step_seconds}
                onChange={(event) => setRainDuration(Number(event.target.value))}
              />
              <small>{time(rainDuration)}</small>
            </label>
            <label>
              <span>
                总降雨量 <small>mm</small>
              </span>
              <input
                value={rainfall}
                type="number"
                min="0"
                step="0.1"
                onChange={(event) => setRainfall(Number(event.target.value))}
              />
              <small>
                当前峰值 {rainOptions.peak_rainfall_mm_h.toFixed(2)} mm/h
              </small>
            </label>
            <div className="rainfall-derived">
              <span>降雨结束</span>
              <strong>{time(rainStart + rainDuration)}</strong>
              <small>峰现系数 {rainOptions.peak_ratio}</small>
            </div>
          </div>
        </div>
      )}
      <div className="engineering-heading tuning-heading">
        <div>
          <h3>工程参数修改</h3>
        </div>
        {draftsList.length > 0 && <span>{draftsList.length} 项待保存</span>}
      </div>
      <div className="selection-mode" aria-label="选择方式">
        <button
          type="button"
          className={mode === 'single' ? 'active' : ''}
          onClick={() => setMode('single')}
        >
          单个选择
        </button>
        <button
          type="button"
          className={mode === 'batch' ? 'active' : ''}
          onClick={() => {
            setMode('batch');
            if (!targets.length && target) setTargets([target]);
          }}
        >
          批量选择 {targets.length > 0 && <b>{targets.length}</b>}
        </button>
      </div>
      <div className="group-tabs" role="tablist" aria-label="对象类型">
        {groups.map((item) => (
          <button
            key={item.id}
            type="button"
            className={item.id === groupId ? 'active' : ''}
            onClick={() => {
              setGroupId(item.id);
              setSearch('');
            }}
          >
            {item.label} <b>{item.objects.length}</b>
          </button>
        ))}
      </div>
      {group && (
        <div className="object-picker">
          <input
            value={search}
            type="search"
            placeholder="搜索对象编号"
            onChange={(event) => setSearch(event.target.value)}
          />
          {mode === 'single' ? (
            <select
              value={target}
              size={5}
              onChange={(event) => setTarget(event.target.value)}
            >
              {filtered.map((item) => (
                <option key={item.target} value={item.target}>
                  {item.target}
                </option>
              ))}
            </select>
          ) : (
            <div className="batch-object-list">
              <div className="batch-list-actions">
                <button
                  type="button"
                  onClick={() =>
                    setTargets(
                      Array.from(new Set([...targets, ...filtered.map((item) => item.target)])),
                    )
                  }
                >
                  全选搜索结果
                </button>
                <button type="button" onClick={() => setTargets([])}>
                  清空
                </button>
              </div>
              {filtered.map((item) => (
                <label
                  key={item.target}
                >
                  <input
                    type="checkbox"
                    checked={targets.includes(item.target)}
                    onChange={() =>
                      setTargets((current) =>
                        current.includes(item.target)
                          ? current.filter((value) => value !== item.target)
                          : [...current, item.target],
                      )
                    }
                  />
                  <span>{item.target}</span>
                </label>
              ))}
              {filtered.length === 0 && <p>没有匹配对象</p>}
            </div>
          )}
        </div>
      )}
      {mode === 'single' && object && (
        <div className="object-editor">
          <div className="object-identity">
            <span>当前对象</span>
            <strong>{object.target}</strong>
            <em>也可直接点击地图要素切换</em>
          </div>
          <div className="field-grid">
            {object.fields.map((field) => (
              <label key={field.key}>
                <span>
                  {field.label} <small>{field.unit}</small>
                </span>
                <input
                  type="number"
                  value={value(field)}
                  min={field.minimum}
                  max={field.maximum}
                  step={field.step}
                  onChange={(event) => stage(field, event.target.value)}
                />
                <small>
                  {field.minimum} ～ {field.maximum} {field.unit}
                </small>
              </label>
            ))}
          </div>
        </div>
      )}
      {mode === 'batch' && targets.length > 0 && (
        <div className="batch-editor">
          <div className="batch-editor-heading">
            <div>
              <strong>
                已选择 {targets.length} 个{group?.label}
              </strong>
            </div>
          </div>
          {commonFields.length ? (
            <div className="batch-controls">
              <label>
                <span>调整参数</span>
                <select value={batchKey} onChange={(event) => setBatchKey(event.target.value)}>
                  {commonFields.map((field) => (
                    <option key={field.key} value={field.key}>
                      {field.label} {field.unit ? `(${field.unit})` : ''}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                <span>调整方式</span>
                <select
                  value={batchOperation}
                  onChange={(event) =>
                    setBatchOperation(event.target.value as typeof batchOperation)
                  }
                >
                  <option value="set">设置为</option>
                  <option value="add">增加 / 减少</option>
                  <option value="percent">按比例调整</option>
                </select>
              </label>
              <label>
                <span>{batchOperation === 'percent' ? '调整比例' : '数值'}</span>
                <div className="batch-value-input">
                  <input
                    value={batchAmount}
                    type="number"
                    step={batchField?.step ?? 'any'}
                    onChange={(event) => setBatchAmount(event.target.value)}
                  />
                  <small>{batchOperation === 'percent' ? '%' : batchField?.unit}</small>
                </div>
              </label>
              <button type="button" onClick={applyBatch}>
                计算并加入变更预览
              </button>
            </div>
          ) : (
            <p className="no-common-fields">
              所选对象没有共同的可调参数，请选择同一种节点类型。
            </p>
          )}
        </div>
      )}
      {error && (
        <p className="tuning-error" role="alert">
          {error}
        </p>
      )}
      {draftsList.length || durationChanged || stepChanged || rainChanged ? (
        <div className="change-ruler">
          <div className="change-ruler-title">
            <span>变更预览</span>
            <button type="button" onClick={clear}>
              全部撤销
            </button>
          </div>
          {durationChanged && (
            <Change
              label="模拟时长"
              oldValue={`${options?.duration_seconds} 秒`}
              newValue={`${duration} 秒`}
              onRemove={() => setDuration(options?.duration_seconds ?? 0)}
            />
          )}
          {stepChanged && (
            <Change
              label="输出步长"
              oldValue={`${options?.report_step_seconds} 秒`}
              newValue={`${reportStep} 秒`}
              onRemove={() => setReportStep(options?.report_step_seconds ?? 0)}
            />
          )}
          {rainChanged && (
            <Change
              label="设计降雨"
              oldValue={`${time(rainOptions!.start_seconds)}–${time(rainOptions!.start_seconds + rainOptions!.duration_seconds)} · ${rainOptions!.total_rainfall_mm} mm`}
              newValue={`${time(rainStart)}–${time(rainStart + rainDuration)} · ${rainfall} mm`}
              onRemove={() => {
                setRainStart(rainOptions!.start_seconds);
                setRainDuration(rainOptions!.duration_seconds);
                setRainfall(rainOptions!.total_rainfall_mm);
              }}
            />
          )}
          {draftsList.map((draft) => (
            <Change
              key={draft.key}
              label={`${draft.target} · ${draft.label}`}
              oldValue={draft.oldValue}
              newValue={`${draft.newValue} ${draft.unit}`}
              onRemove={() =>
                setDrafts((current) => {
                  const next = { ...current };
                  delete next[draft.key];
                  return next;
                })
              }
            />
          ))}
          <input
            value={summary}
            maxLength={500}
            placeholder="版本说明，例如：降低管线粗糙度"
            onChange={(event) => setSummary(event.target.value)}
          />
          <button
            className="save-version"
            type="button"
            disabled={store.savingVersion || !!error}
            onClick={() => void save()}
          >
            {store.savingVersion ? '正在校验并生成…' : `校验并生成 V${nextVersion}`}
          </button>
        </div>
      ) : null}
      {created && (
        <div className="version-created">
          <div>
            <strong>新版本 V{created.version} 已生成</strong>
          </div>
          <button type="button" disabled={store.running} onClick={() => void runCreated()}>
            {store.running ? '正在运行…' : `运行 V${created.version}`}
          </button>
        </div>
      )}
    </section>
  );
}
function Change({
  label,
  oldValue,
  newValue,
  onRemove,
}: {
  label: string;
  oldValue: string;
  newValue: string;
  onRemove: () => void;
}) {
  return (
    <div className="change-line">
      <span>{label}</span>
      <code>{oldValue}</code>
      <i>→</i>
      <code>{newValue}</code>
      <button type="button" onClick={onRemove}>
        ×
      </button>
    </div>
  );
}

// MapboxProject/src/components/ParameterTuning.vue
<template>
  <section class="tuning-workspace" aria-label="参数设置">
    <div class="tuning-heading">
      <div>
        <h3>模拟参数设置</h3>
      </div>
      <span v-if="simulationOptionsChanged || rainfallOptionsChanged">
        {{ Number(simulationDurationChanged) + Number(reportStepChanged) + Number(rainfallOptionsChanged) }} 项待保存
      </span>
    </div>

    <div v-if="store.simulationOptions" class="simulation-settings">
      <div class="simulation-setting-fields">
        <label>
          <span>模拟时长 <small>秒</small></span>
          <input
            v-model.number="durationSeconds"
            type="number"
            :min="store.simulationOptions.duration_min_seconds"
            :max="store.simulationOptions.duration_max_seconds"
            step="1"
          />
          <small>
            {{ store.simulationOptions.duration_min_seconds }}～{{ store.simulationOptions.duration_max_seconds }} 秒
          </small>
        </label>
        <label>
          <span>输出步长 <small>秒</small></span>
          <input
            v-model.number="reportStepSeconds"
            type="number"
            :min="effectiveReportStepMinimum"
            :max="durationSeconds || undefined"
            step="1"
          />
          <small>不小于路由步长 {{ store.simulationOptions.routing_step_seconds }} 秒</small>
        </label>
      </div>
      <div class="simulation-projection">
        <span>预计结束</span>
        <strong>{{ estimatedEndTime }}</strong>
        <output>{{ estimatedOutputSteps }} 个输出点</output>
        <em v-if="store.simulationOptions.require_report_step_divisible">时长须能被输出步长整除</em>
      </div>
    </div>

    
    <div v-if="store.rainfallOptions" class="rainfall-settings">
      <div class="rainfall-setting-fields">
        <label>
          <span>降雨开始 <small>秒</small></span>
          <input v-model.number="rainStartSeconds" type="number" min="0" :max="durationSeconds" :step="store.rainfallOptions.time_step_seconds" />
          <small>{{ formatOffset(rainStartSeconds) }}</small>
        </label>
        <label>
          <span>降雨时长 <small>秒</small></span>
          <input v-model.number="rainDurationSeconds" type="number" min="0" :max="Math.max(0, durationSeconds - rainStartSeconds)" :step="store.rainfallOptions.time_step_seconds" />
          <small>{{ formatOffset(rainDurationSeconds) }}</small>
        </label>
        <label>
          <span>总降雨量 <small>mm</small></span>
          <input v-model.number="rainTotalRainfallMm" type="number" min="0" step="0.1" />
          <small>当前峰值 {{ store.rainfallOptions.peak_rainfall_mm_h.toFixed(2) }} mm/h</small>
        </label>
        <div class="rainfall-derived">
          <span>降雨结束</span>
          <strong>{{ formatOffset(rainStartSeconds + rainDurationSeconds) }}</strong>
          <small>峰现系数 {{ store.rainfallOptions.peak_ratio }}</small>
        </div>
      </div>
    </div>

    <div class="engineering-heading tuning-heading">
      <div>
        <h3>工程参数修改</h3>
      </div>
      <span v-if="draftsList.length">{{ draftsList.length }} 项待保存</span>
    </div>

    <div class="selection-mode" aria-label="选择方式">
      <button type="button" :class="{ active: selectionMode === 'single' }" @click="setSelectionMode('single')">
        单个选择
      </button>
      <button type="button" :class="{ active: selectionMode === 'batch' }" @click="setSelectionMode('batch')">
        批量选择 <b v-if="selectedTargets.length">{{ selectedTargets.length }}</b>
      </button>
    </div>

    <div class="group-tabs" role="tablist" aria-label="对象类型">
      <button
        v-for="group in groups"
        :key="group.id"
        type="button"
        :class="{ active: group.id === selectedGroupId }"
        @click="selectGroup(group.id)"
      >
        {{ group.label }} <b>{{ group.objects.length }}</b>
      </button>
    </div>

    <div v-if="activeGroup" class="object-picker">
      <input v-model.trim="search" type="search" placeholder="搜索对象编号" aria-label="搜索对象编号" />
      <select v-if="selectionMode === 'single'" v-model="selectedTarget" size="5" aria-label="选择调参对象">
        <option v-for="item in filteredObjects" :key="item.target" :value="item.target">
          {{ item.target }}
        </option>
      </select>
      <div v-else class="batch-object-list">
        <div class="batch-list-actions">
          <button type="button" @click="selectFilteredObjects">全选搜索结果</button>
          <button type="button" @click="clearObjectSelection">清空</button>
        </div>
        <label v-for="item in filteredObjects" :key="item.target">
          <input
            type="checkbox"
            :checked="selectedTargets.includes(item.target)"
            @change="toggleTarget(item.target)"
          />
          <span>{{ item.target }}</span>
        </label>
        <p v-if="!filteredObjects.length">没有匹配对象</p>
      </div>
    </div>

    <div v-if="selectionMode === 'single' && selectedObject" class="object-editor">
      <div class="object-identity">
        <span>当前对象</span>
        <strong>{{ selectedObject.target }}</strong>
        <em>也可直接点击地图要素切换</em>
      </div>
      <div class="field-grid">
        <label v-for="field in selectedObject.fields" :key="field.key">
          <span>{{ field.label }} <small>{{ field.unit }}</small></span>
          <input
            type="number"
            :value="draftValue(field)"
            :min="field.minimum"
            :max="field.maximum"
            :step="field.step"
            @change="stageField(field, $event)"
          />
          <small>{{ field.minimum }} ～ {{ field.maximum }} {{ field.unit }}</small>
        </label>
      </div>
    </div>

    <div v-if="selectionMode === 'batch' && selectedTargets.length" class="batch-editor">
      <div class="batch-editor-heading">
        <div>
          <strong>已选择 {{ selectedTargets.length }} 个{{ activeGroup?.label }}</strong>
        </div>
      </div>
      <div v-if="commonFields.length" class="batch-controls">
        <label>
          <span>调整参数</span>
          <select v-model="batchFieldKey">
            <option v-for="field in commonFields" :key="field.key" :value="field.key">
              {{ field.label }} {{ field.unit ? `(${field.unit})` : '' }}
            </option>
          </select>
        </label>
        <label>
          <span>调整方式</span>
          <select v-model="batchOperation">
            <option value="set">设置为</option>
            <option value="add">增加 / 减少</option>
            <option value="percent">按比例调整</option>
          </select>
        </label>
        <label>
          <span>{{ batchOperation === 'percent' ? '调整比例' : '数值' }}</span>
          <div class="batch-value-input">
            <input v-model="batchAmount" type="number" :step="batchField?.step || 'any'" />
            <small>{{ batchOperation === 'percent' ? '%' : batchField?.unit }}</small>
          </div>
        </label>
        <button type="button" @click="applyBatchChange">计算并加入变更预览</button>
      </div>
      <p v-else class="no-common-fields">所选对象没有共同的可调参数，请选择同一种节点类型。</p>
    </div>

    <p v-if="displayError" class="tuning-error" role="alert">{{ displayError }}</p>

    <div v-if="pendingChangeCount" class="change-ruler">
      <div class="change-ruler-title">
        <span>变更预览</span>
        <button type="button" @click="clearDrafts">全部撤销</button>
      </div>
      <div v-if="simulationDurationChanged" class="change-line">
        <span>模拟时长</span>
        <code>{{ store.simulationOptions?.duration_seconds }} 秒</code>
        <i>→</i>
        <code>{{ durationSeconds }} 秒</code>
        <button type="button" aria-label="撤销模拟时长修改" @click="resetDuration">×</button>
      </div>
      <div v-if="reportStepChanged" class="change-line">
        <span>输出步长</span>
        <code>{{ store.simulationOptions?.report_step_seconds }} 秒</code>
        <i>→</i>
        <code>{{ reportStepSeconds }} 秒</code>
        <button type="button" aria-label="撤销输出步长修改" @click="resetReportStep">×</button>
      </div>
      <div v-if="rainfallOptionsChanged" class="change-line">
        <span>设计降雨</span>
        <code>{{ rainfallSummary(store.rainfallOptions?.start_seconds, store.rainfallOptions?.duration_seconds, store.rainfallOptions?.total_rainfall_mm) }}</code>
        <i>→</i>
        <code>{{ rainfallSummary(rainStartSeconds, rainDurationSeconds, rainTotalRainfallMm) }}</code>
        <button type="button" aria-label="撤销设计降雨修改" @click="resetRainfall">×</button>
      </div>
      <div v-for="draft in draftsList" :key="draft.key" class="change-line">
        <span>{{ draft.target }} · {{ draft.label }}</span>
        <code>{{ draft.oldValue }}</code>
        <i>→</i>
        <code>{{ draft.newValue }} {{ draft.unit }}</code>
        <button type="button" aria-label="撤销该项" @click="removeDraft(draft.key)">×</button>
      </div>
      <input v-model.trim="summary" maxlength="500" placeholder="版本说明，例如：降低管线粗糙度" />
      <button class="save-version" type="button" :disabled="store.savingVersion || !!combinedOptionsError" @click="saveVersion">
        {{ store.savingVersion ? '正在校验并生成…' : `校验并生成 V${nextVersionNumber}` }}
      </button>
    </div>

    <div v-if="createdVersion" class="version-created">
      <div>
        <strong>新版本 V{{ createdVersion.version }} 已生成</strong>
      </div>
      <button type="button" :disabled="store.running" @click="runCreatedVersion">
        {{ store.running ? '正在运行…' : `运行 V${createdVersion.version}` }}
      </button>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import type { EditableField, ModelVersion } from '@/api/models'
import eventBus from '@/eventBus'
import { useModelStore } from '@/stores/modelStore'

interface Draft {
  key: string
  section: string
  target: string
  field: string
  label: string
  unit: string
  oldValue: string
  newValue: string
}

const store = useModelStore()
const selectedGroupId = ref('')
const selectedTarget = ref('')
const selectedTargets = ref<string[]>([])
const selectionMode = ref<'single' | 'batch'>('single')
const search = ref('')
const summary = ref('')
const drafts = ref<Record<string, Draft>>({})
const localError = ref('')
const createdVersion = ref<ModelVersion | null>(null)
const batchFieldKey = ref('')
const batchOperation = ref<'set' | 'add' | 'percent'>('set')
const batchAmount = ref('')
const durationSeconds = ref(0)
const reportStepSeconds = ref(0)
const rainStartSeconds = ref(0)
const rainDurationSeconds = ref(0)
const rainTotalRainfallMm = ref(0)

const groups = computed(() => store.parameterGroups)
const activeGroup = computed(() => groups.value.find((group) => group.id === selectedGroupId.value))
const filteredObjects = computed(() => {
  const query = search.value.toLowerCase()
  return (activeGroup.value?.objects || []).filter((item) => item.target.toLowerCase().includes(query))
})
const selectedObject = computed(() =>
  activeGroup.value?.objects.find((item) => item.target === selectedTarget.value),
)
const selectedBatchObjects = computed(() =>
  (activeGroup.value?.objects || []).filter((item) => selectedTargets.value.includes(item.target)),
)
const commonFields = computed(() => {
  const objects = selectedBatchObjects.value
  const firstObject = objects[0]
  if (!firstObject) return []
  return firstObject.fields.filter((field) =>
    objects.every((item) => item.fields.some((candidate) => candidate.key === field.key)),
  )
})
const batchField = computed(() => commonFields.value.find((field) => field.key === batchFieldKey.value))
const filteredSelectedCount = computed(() =>
  filteredObjects.value.filter((item) => selectedTargets.value.includes(item.target)).length,
)
const draftsList = computed(() => Object.values(drafts.value))
const simulationDurationChanged = computed(
  () => durationSeconds.value !== store.simulationOptions?.duration_seconds,
)
const reportStepChanged = computed(
  () => reportStepSeconds.value !== store.simulationOptions?.report_step_seconds,
)
const simulationOptionsChanged = computed(
  () => simulationDurationChanged.value || reportStepChanged.value,
)
const rainfallOptionsChanged = computed(() => {
  const options = store.rainfallOptions
  return !!options && (
    rainStartSeconds.value !== options.start_seconds ||
    rainDurationSeconds.value !== options.duration_seconds ||
    rainTotalRainfallMm.value !== options.total_rainfall_mm
  )
})
const pendingChangeCount = computed(
  () => draftsList.value.length + Number(simulationDurationChanged.value) + Number(reportStepChanged.value) + Number(rainfallOptionsChanged.value),
)
const effectiveReportStepMinimum = computed(() =>
  Math.max(
    store.simulationOptions?.report_step_min_seconds || 1,
    Math.ceil(store.simulationOptions?.routing_step_seconds || 0),
  ),
)
const estimatedOutputSteps = computed(() => {
  if (!Number.isInteger(durationSeconds.value) || !Number.isInteger(reportStepSeconds.value) || reportStepSeconds.value <= 0) return '—'
  return Math.floor(durationSeconds.value / reportStepSeconds.value)
})
const estimatedEndTime = computed(() => {
  const start = store.simulationOptions?.start_datetime
  if (!start || !Number.isInteger(durationSeconds.value) || durationSeconds.value <= 0) return '—'
  return formatDateTime(new Date(parseSimulationDate(start).getTime() + durationSeconds.value * 1000).toISOString())
})
const simulationError = computed(() => {
  const options = store.simulationOptions
  const duration = durationSeconds.value
  const reportStep = reportStepSeconds.value
  if (!options) return ''
  if (!Number.isInteger(duration)) return '模拟时长必须是整数秒'
  if (duration < options.duration_min_seconds || duration > options.duration_max_seconds) {
    return `模拟时长必须在 ${options.duration_min_seconds}～${options.duration_max_seconds} 秒之间`
  }
  if (!Number.isInteger(reportStep)) return '输出步长必须是整数秒'
  if (reportStep < effectiveReportStepMinimum.value) return `输出步长不能小于 ${effectiveReportStepMinimum.value} 秒`
  if (reportStep > duration) return '输出步长不能大于模拟时长'
  if (options.require_report_step_divisible && duration % reportStep !== 0) return '模拟时长必须能被输出步长整除'
  if (Math.floor(duration / reportStep) > options.max_output_steps) return `输出时间点不能超过 ${options.max_output_steps} 个`
  return ''
})
const rainfallError = computed(() => {
  const options = store.rainfallOptions
  if (!options) return ''
  if (!Number.isInteger(rainStartSeconds.value) || !Number.isInteger(rainDurationSeconds.value)) return '降雨开始时间和时长必须是整数秒'
  if (rainStartSeconds.value < 0 || rainDurationSeconds.value <= 0) return '降雨开始时间必须不小于 0，降雨时长必须大于 0'
  if (rainStartSeconds.value + rainDurationSeconds.value > durationSeconds.value) return '降雨结束时间不能超过模拟时长'
  if (rainStartSeconds.value % options.time_step_seconds || rainDurationSeconds.value % options.time_step_seconds) return `降雨开始时间和时长必须是 ${options.time_step_seconds} 秒的整数倍`
  if (!Number.isFinite(rainTotalRainfallMm.value) || rainTotalRainfallMm.value <= 0) return '总降雨量必须是大于 0 的有效数值'
  return ''
})
const combinedOptionsError = computed(() => simulationError.value || rainfallError.value)
const displayError = computed(() => localError.value || combinedOptionsError.value)
const nextVersionNumber = computed(() => Math.max(...store.versions.map((item) => item.version), 0) + 1)

watch(
  () => store.simulationOptions,
  (options) => {
    durationSeconds.value = options?.duration_seconds || 0
    reportStepSeconds.value = options?.report_step_seconds || 0
  },
  { immediate: true },
)

watch(
  () => store.rainfallOptions,
  (options) => {
    rainStartSeconds.value = options?.start_seconds || 0
    rainDurationSeconds.value = options?.duration_seconds || 0
    rainTotalRainfallMm.value = options?.total_rainfall_mm || 0
  },
  { immediate: true },
)

watch(
  groups,
  (value) => {
    if (!value.some((group) => group.id === selectedGroupId.value)) {
      selectedGroupId.value = value[0]?.id || ''
      selectedTarget.value = value[0]?.objects[0]?.target || ''
    }
  },
  { immediate: true },
)

watch(activeGroup, (group) => {
  if (!group?.objects.some((item) => item.target === selectedTarget.value)) {
    selectedTarget.value = group?.objects[0]?.target || ''
  }
  selectedTargets.value = []
})

watch(commonFields, (fields) => {
  if (!fields.some((field) => field.key === batchFieldKey.value)) {
    batchFieldKey.value = fields[0]?.key || ''
  }
})

watch(
  () => store.selectedVersionId,
  () => {
    clearDrafts()
    createdVersion.value = null
  },
)

function selectGroup(groupId: string) {
  selectedGroupId.value = groupId
  search.value = ''
}

function setSelectionMode(mode: 'single' | 'batch') {
  selectionMode.value = mode
  localError.value = ''
  if (mode === 'batch' && !selectedTargets.value.length && selectedTarget.value) {
    selectedTargets.value = [selectedTarget.value]
  }
}

function toggleTarget(target: string) {
  selectedTargets.value = selectedTargets.value.includes(target)
    ? selectedTargets.value.filter((item) => item !== target)
    : [...selectedTargets.value, target]
}

function selectFilteredObjects() {
  selectedTargets.value = Array.from(
    new Set([...selectedTargets.value, ...filteredObjects.value.map((item) => item.target)]),
  )
}

function clearObjectSelection() {
  selectedTargets.value = []
}

function draftKey(field: EditableField) {
  return `${field.section}|${selectedObject.value?.target}|${field.field}`
}

function draftKeyFor(target: string, field: EditableField) {
  return `${field.section}|${target}|${field.field}`
}

function draftValue(field: EditableField) {
  return drafts.value[draftKey(field)]?.newValue ?? field.value
}

function stageField(field: EditableField, event: Event) {
  const input = event.target as HTMLInputElement
  const value = Number(input.value)
  localError.value = ''
  if (!Number.isFinite(value) || value < field.minimum || value > field.maximum) {
    localError.value = `${field.label}必须在 ${field.minimum}～${field.maximum} ${field.unit} 之间`
    input.value = draftValue(field)
    return
  }
  const normalized = String(value)
  const key = draftKey(field)
  if (normalized === String(Number(field.value))) {
    removeDraft(key)
    return
  }
  drafts.value[key] = {
    key,
    section: field.section,
    target: selectedObject.value!.target,
    field: field.field,
    label: field.label,
    unit: field.unit,
    oldValue: field.value,
    newValue: normalized,
  }
}

function applyBatchChange() {
  const fieldTemplate = batchField.value
  const amount = Number(batchAmount.value)
  localError.value = ''
  if (!fieldTemplate || !Number.isFinite(amount)) {
    localError.value = '请选择参数并输入有效数值'
    return
  }

  const updates: Array<{ key: string; draft?: Draft }> = []
  for (const item of selectedBatchObjects.value) {
    const field = item.fields.find((candidate) => candidate.key === fieldTemplate.key)
    if (!field) continue
    const key = draftKeyFor(item.target, field)
    const existingDraft = drafts.value[key]
    const current = Number(existingDraft?.newValue ?? field.value)
    let next = amount
    if (batchOperation.value === 'add') next = current + amount
    if (batchOperation.value === 'percent') next = current * (1 + amount / 100)
    next = Number(next.toPrecision(12))
    if (!Number.isFinite(next) || next < field.minimum || next > field.maximum) {
      localError.value = `${item.target} 的${field.label}计算后为 ${next}，超出 ${field.minimum}～${field.maximum} ${field.unit}`
      return
    }
    if (next === Number(field.value)) {
      if (existingDraft) updates.push({ key })
    } else if (next !== current) {
      updates.push({
        key,
        draft: {
          key,
          section: field.section,
          target: item.target,
          field: field.field,
          label: field.label,
          unit: field.unit,
          oldValue: field.value,
          newValue: String(next),
        },
      })
    }
  }

  if (!updates.length) {
    localError.value = '计算后的参数没有发生变化'
    return
  }
  const copy = { ...drafts.value }
  updates.forEach(({ key, draft }) => {
    if (draft) copy[key] = draft
    else delete copy[key]
  })
  drafts.value = copy
}

function removeDraft(key: string) {
  const copy = { ...drafts.value }
  delete copy[key]
  drafts.value = copy
}

function clearDrafts() {
  drafts.value = {}
  localError.value = ''
  resetDuration()
  resetReportStep()
  resetRainfall()
}

function resetDuration() {
  durationSeconds.value = store.simulationOptions?.duration_seconds || 0
}

function resetReportStep() {
  reportStepSeconds.value = store.simulationOptions?.report_step_seconds || 0
}

function resetRainfall() {
  rainStartSeconds.value = store.rainfallOptions?.start_seconds || 0
  rainDurationSeconds.value = store.rainfallOptions?.duration_seconds || 0
  rainTotalRainfallMm.value = store.rainfallOptions?.total_rainfall_mm || 0
}

function formatOffset(value: number) {
  if (!Number.isFinite(value)) return '—'
  const seconds = Math.max(0, Math.round(value))
  const hours = Math.floor(seconds / 3600)
  const minutes = Math.floor((seconds % 3600) / 60)
  const remainder = seconds % 60
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(remainder).padStart(2, '0')}`
}

function rainfallSummary(start?: number, duration?: number, totalRainfall?: number) {
  if (start === undefined || duration === undefined || totalRainfall === undefined) return '—'
  return `${formatOffset(start)}–${formatOffset(start + duration)} · ${totalRainfall} mm`
}

function formatDateTime(value: string) {
  const date = parseSimulationDate(value)
  if (Number.isNaN(date.getTime())) return value
  const pad = (part: number) => String(part).padStart(2, '0')
  return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())}:${pad(date.getUTCSeconds())}`
}

function parseSimulationDate(value: string) {
  return new Date(/[zZ]|[+-]\d\d:\d\d$/.test(value) ? value : `${value}Z`)
}

async function saveVersion() {
  const parentId = store.selectedVersionId
  if (!parentId || combinedOptionsError.value) return
  const result = await store.saveAdjustedVersion(
    draftsList.value.map((draft) => ({
      section: draft.section,
      target: draft.target,
      field: draft.field,
      new_value: draft.newValue,
    })),
    summary.value || undefined,
    simulationOptionsChanged.value
      ? {
          duration_seconds: durationSeconds.value,
          report_step_seconds: reportStepSeconds.value,
        }
      : undefined,
    rainfallOptionsChanged.value
      ? {
          start_seconds: rainStartSeconds.value,
          duration_seconds: rainDurationSeconds.value,
          total_rainfall_mm: rainTotalRainfallMm.value,
        }
      : undefined,
  )
  if (!result) return
  createdVersion.value = result.version
  summary.value = ''
  clearDrafts()
}

async function runCreatedVersion() {
  const result = await store.runSelectedVersion()
  if (!result) return
  eventBus.emit('modelRunCompleted', result)
}

async function handleMapSelection(payload: { layerId: string; target: string }) {
  const group = groups.value.find((item) => item.map_layer === payload.layerId)
  if (!group?.objects.some((item) => item.target === payload.target)) return

  const groupChanged = selectedGroupId.value !== group.id
  selectedGroupId.value = group.id
  if (groupChanged) await nextTick()

  if (selectionMode.value === 'batch') {
    if (!selectedTargets.value.includes(payload.target)) {
      selectedTargets.value = [...selectedTargets.value, payload.target]
    }
  } else {
    selectedTarget.value = payload.target
  }
}

onMounted(() => eventBus.on('mapFeatureSelected', handleMapSelection))
onBeforeUnmount(() => eventBus.off('mapFeatureSelected', handleMapSelection))
</script>

<style scoped src="@/assets/css/ParameterTuning.css"></style>
